### ISSUE TITLE
tooltip: column mean not shown over NA samples

### ISSUE THREAD

**Issue by acthp** [ucscXena/ucsc-xena-client#93] opened 2016-05-02 22:47 UTC
When the value for a sample is NA, we don't render the column mean, which causes the tooltip to resize in a distracting manner.

**Comment by jingchunzhu** [comment] 2017-03-04 00:46
@acthp @maryjgoldman is this still problem? I don't see it. maybe you are talking about something else. 
![image](https://cloud.githubusercontent.com/assets/999493/23574195/e63cc83c-0030-11e7-8b70-e629ac0a74d4.png)

**Comment by souravsingh** [comment] 2017-03-12 15:55
@acthp I am interested in helping in the issue. How do I start?

**Comment by maryjgoldman** [comment] 2017-03-13 17:53
@souravsingh Sorry, this issue was fixed by a previous commit and we forgot to close this issue.

**Comment by maryjgoldman** [comment] 2017-03-13 17:58
@souravsingh Never mind! @acthp showed me what he meant. At the bottom of the tooltip when you hover over a sample that has data, it shows the 'Mean (Median)'. 

The fix is to show the mean and median even if you are hovering over a sample that doesn't have data. Just because that particular sample has no data doesn't mean we can't display the mean and median from the column.

Note there will need to be some error handling for when there is no data in the entire column

**Comment by maryjgoldman** [comment] 2017-03-13 17:58
Example here: https://xenabrowser.net/heatmap/?bookmark=9e399fca023f13991825ccb8ad4a6b08

**Comment by acthp** [comment] 2017-03-13 18:03
@souravsingh I believe this is pretty simple. The code here

https://github.com/ucscXena/ucsc-xena-client/blob/master/js/plotDenseMatrix.js#L78

checks if the sample under the mouse pointer has no value, OR the field is an enumeration ('coded'), and does not display the mean in those cases. I think the fix is just to remove the check for no value. Of course we still want to check for enumerations, since there's no useful mean for those columns.

It's curious that the code is like this. There might be some edge case it was protecting against, like if the entire column is null, as Mary said. So it should be tested with a number of datasets.

**Comment by pulkitkkr** [comment] 2018-02-24 03:42
@acthp as you suggested plotDenseMatrix.js resolves this issue and I have tried that, and it works well but I'm unable to reproduce edge case where whole column is null, can you share any plot which can reproduce such scenario

**Comment by pulkitkkr** [comment] 2018-02-25 21:57
😅 @acthp I guess we must close this issue

**Closed** 2018-02-25 22:19 UTC
Labels: help wanted
